#!/bin/bash

## [Set VPN commands]. Setup for Mullvad is done below.
# The first three commands should have direct equivalents for most VPNs.
# The relay_set command assumes <country_code> <city_code> will follow as arguments. See below.
VPN_CONNECT="mullvad connect"
VPN_DISCONNECT="mullvad disconnect"
VPN_GET_STATUS="mullvad status"
VPN_RELAY_SET_LOCATION="mullvad relay set location"

## [Set VPN status parsing]
# The first command cuts the status, which is compared to keywords below.
# Note from Julia: this should cover most VPNs, if it's missing something let me know
VPN_STATUS="$($VPN_GET_STATUS | grep -Eio 'connected|connecting|disconnected' \
	| tr '[:upper:]' '[:lower:]')"
CONNECTED="connected"
CONNECTING="connecting"

## VPN Icons
ICON_CONNECTED=""
ICON_DISCONNECTE=""

vpn_status() {
    if [ "$VPN_STATUS" = "$CONNECTED"  ]; then
        echo "${ICON_CONNECTED}"
    else
        echo "${ICON_DISCONNECTED}"
    fi
}

case $1 in
    -s|--status) vpn_status ;;
    *) vpn_status ;;
esac
