#!/usr/bin/env zsh

################################################################################
#                   PLACE FOR DEFINING CUSTOM ZSH FUNCTIONS                    #
################################################################################
# NOTE: These functions will be synced in dotfiles.
# For local functions (e.g: work computer), please create a file ending in
# `.local` in the same directory


mcd() {
    mkdir -p "$@" && cd "$@"
}
