#! /bin/sh

#sxhkd &
#~/bin/reload-bar 
#feh --bg-tile ~/Pictures/Desktop/pep.png
#msi-keyboard -m normal -c left,yellow,high -c middle,orange,high -c right,red,high
#twmnd &
#compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --shadow-exclude "! name~=''" &

export SXHKD_SHELL=/bin/zsh
sxhkd -c ~/.config/sxhkd/sxhkdrc_bspwm &
~/.config/polybar/launch.sh

~/Build/Discord/Discord &
spotify &

nextcloud &

bspc monitor $MONITOR_1 -d 1 2 3 4 5 6 7 8
bspc monitor $MONITOR_2 -d 9 10

bspc config window_gap      0
bspc config border_width	6
bspc config top_padding		26

bspc config focused_border_color $(echo \#$(~/.scripts/getcol 1))
bspc config active_border_color $(echo \#$(~/.scripts/getcol 1))
bspc config normal_border_color $(echo \#$(~/.scripts/getcol 4))

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance 	true
#bspc config history_aware_focus	true
bspc wm --record-history on;

#bspc config external_rules_command "./.config/bspwm/bspwm-floating"
bspc config external_rules_command "./.config/bspwm/bspwm-rules"

bspc config focus_follows_pointer true

#bspc rule -a Screenkey manage=off
