#! /bin/bash

#sxhkd &
#~/bin/reload-bar 
#msi-keyboard -m normal -c left,yellow,high -c middle,orange,high -c right,red,high
#twmnd &
#compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --shadow-exclude "! name~=''" & 
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config window_gap 0
bspc config top_monocle_padding 0
bpsc config left_monocle_padding 0
bpsc config right_monocle_padding 0 bpsc config bottom_monocle_padding 0

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance 	true
#bspc config history_aware_focus	true
bspc wm --record-history on;

bspc config external_rules_command "./.config/bspwm/bspwm-rules"

bspc config focus_follows_pointer true

#bspc rule -a Screenkey manage=off

xset +fp /home/andy/.local/share/fonts
xset fp rehash

xinput map-to-output 10 eDP-1

#export SXHKD_SHELL=/bin/zsh
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends --vsync &

#wal --theme gruvbox-hard
wal -R
wal-set

. "${HOME}/.cache/wal/colors.sh"

# If HDMI monitor is connected, create two polybar instances and place monitors
if [ "$(cat /sys/class/drm/card0-HDMI-A-1/status)" == "connected" ];
then
    ~/.screenlayout/dual_monitor.sh
else
    polybar mainbar -r &
fi

bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color1"

wmname LG3D
