-- The docs for this file were generated by qwen2.5-coder:32b while testing this config lol
-- Local module for configuring the Avante plugin
local M = {}

-- Configuration function for additional setup (currently empty)
M.config = function()
end

-- Options table to configure the Avante plugin
M.opts = {
    -- Specify the provider to use (e.g., "ollama")
    provider = "ollama",
    ollama = {
        -- Name of the API key environment variable
        api_key_name = "",
        -- Endpoint URL for the Ollama service
        endpoint = "http://127.0.0.1:11434",
        -- Model to use (e.g., "qwen2.5-coder:32b")
        -- model = "qwen2.5-coder:32b",
        model = "qwen2.5-coder:14b-instruct-q4_K_M",
        options = {
            -- Number of context tokens
            num_ctx = 32768,
            -- num_ctx = 8192,
            -- Temperature for randomness in output
            temperature = 0,
        },
        -- Enable streaming responses
        stream = true,
    },
}

-- Return the configured module
return M
