#! /bin/bash

source "${HOME}/.config/bspwm/bspwm-config"

bspc config external_rules_command "${HOME}/.config/bspwm/bspwm-rules"

bspc config border_width 3
bspc config window_gap 0
bspc config top_monocle_padding 0
bspc config left_monocle_padding 0
bspc config right_monocle_padding 0
bpsc config bottom_monocle_padding 0

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
#bspc config focus_by_distance 	true
#bspc config history_aware_focus	true
bspc wm --record-history on;

bspc config focus_follows_pointer true

#bspc rule -a Screenkey manage=off

xset +fp /home/andy/.local/share/fonts
xset fp rehash

############
#  COLORS  #
############

wal -R
wal-set

bspc config normal_border_color $BSPWM_COLOR_BORDER_NORM
bspc config active_border_color $BSPWM_COLOR_BORDER_NORM
bspc config focused_border_color $BSPWM_COLOR_BORDER_FOCUS
bspc config presel_feedback_color $BSPWM_COLOR_PRESELECT

##################
#  CONFIG SETUP  #
##################

export SXHKD_SHELL=/bin/zsh
pgrep -x sxhkd > /dev/null || sxhkd &

eval $BSPWM_COMPOSITOR_COMMAND
eval $BSPWM_MONITOR_SETUP
eval $BSPWM_AUTOSTART

wmname LG3D
