#! python3

import pyautogui, sys
import argparse

parser = argparse.ArgumentParser(description='Runescape nifty clicker')

parser.add_argument('--pos', nargs='3', help='Specify the [x] and [y] position for clicking')

args = parser.parse_args()
