-- The docs for this file were generated by qwen2.5-coder:32b while testing this config lol
-- Local module for configuring the Avante plugin
local M = {}

-- Configuration function for additional setup (currently empty)
M.config = function() end

-- Options table to configure the Avante plugin
M.opts = {
    -- Specify the provider to use (e.g., "ollama")
    provider = "ollama",
    providers = {
        ollama = {
            -- Name of the API key environment variable
            api_key_name = "",
            -- Endpoint URL for the Ollama service
            endpoint = "http://127.0.0.1:11434",
            -- model = "qwen2.5-coder:32b",
            model = "qwen2.5-coder:14b-instruct-q4_K_M",
            extra_request_body = {
                options = {
                    -- Number of context tokens
                    num_ctx = 32768,
                    -- num_ctx = 8192,
                    -- Temperature for randomness in output
                    temperature = 0,
                },
            },
            -- Enable streaming responses
            stream = true,
        },
    },
}

----------------
--  AI STUFF  --
----------------
-- I really don't want this stuff in here,
-- but I guess this is the future :(
return {
    { -- AI Coding Companion
        "yetone/avante.nvim",
        event = "VeryLazy",
        lazy = true,
        version = false, -- Set this to "*" to always pull the latest release version, or set it to false to update to the latest code changes.
        opts = M.opts,
        -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
        build = "make",
        -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
        dependencies = {
            "nvim-treesitter/nvim-treesitter",
            "stevearc/dressing.nvim",
            "nvim-lua/plenary.nvim",
            "MunifTanjim/nui.nvim",
            --- The below dependencies are optional,
            -- "echasnovski/mini.pick", -- for file_selector provider mini.pick
            "nvim-telescope/telescope.nvim", -- for file_selector provider telescope
            -- "hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
            -- "ibhagwan/fzf-lua", -- for file_selector provider fzf
            "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
            -- "zbirenbaum/copilot.lua", -- for providers='copilot'
            -- {
            --     -- support for image pasting
            --     "HakonHarnes/img-clip.nvim",
            --     event = "VeryLazy",
            --     opts = {
            --         -- recommended settings
            --         default = {
            --             embed_image_as_base64 = false,
            --             prompt_for_file_name = false,
            --             drag_and_drop = {
            --                 insert_mode = true,
            --             },
            --             -- required for Windows users
            --             use_absolute_path = true,
            --         },
            --     },
            -- },
            {
                -- Make sure to set this up properly if you have lazy=true
                "MeanderingProgrammer/render-markdown.nvim",
                opts = {
                    file_types = { "markdown", "Avante" },
                },
                ft = { "markdown", "Avante" },
            },
        },
    },
}
