#!/usr/bin/env bash

# How to use this with godot:
# In Godot: Editor > Editor Settings > (General Tab) > Text Editor > External
# External Editor = Yes
# Exec Path = <absolute path to this script/or godot-nvim if its in path>
# Exec Flags = "{file}" "{line},{col}"

nvim_exec="nvim"
server_path="/tmp/nvim/godot-server.pipe"

start_server() {
    tmux new -d -s godot "$nvim_exec +GodotServer --listen $server_path $1"
}

open_file_in_server() {
    $nvim_exec --server "$server_path" --remote-send "<C-\><C-n>:n $1<CR>:call cursor($2)<CR>"
}

if ! [ -e "$server_path" ]; then
    start_server "$1"
else
    open_file_in_server "$1" "$2"
fi
